version: 2
ethernets:
  DEVICE:
    match:
      # name: "DEVICE"
      macaddress: "MACADDRESS"
    dhcp4: DHCP
    addresses: [ADDRESS]
    mtu: 1500
    gateway4: SUBNET_GATEWAY
    nameservers:
      addresses: NAMESERVERS
    routes:
      - to: 0.0.0.0
        via: DEFAULT_GATEWAY
