version: 2
ethernets:
  TEMPLATE_DEVICE:
    match:
      # name: "DEVICE"
      macaddress: "TEMPLATE_MACADDRESS"
    dhcp4: TEMPLATE_DHCP4
    addresses: [TEMPLATE_ADDRESS4]
    mtu: 1500
    gateway4: TEMPLATE_SUBNET_GATEWAY4
    nameservers:
      addresses: TEMPLATE_NAMESERVERS
    routes:
      - to: 0.0.0.0
        via: TEMPLATE_DEFAULT_GATEWAY4
