name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install packages
        run: |
          set -eux
          sudo apt update
          sudo apt install --yes \
            python3-pip \
            qemu-system \
            libvirt-daemon-system
          sudo usermod --append --groups libvirt $(id --user --name)
          pip install bashate

      - name: Lint
        run: bashate --verbose --ignore E006 --ignore E044 *.sh

      - name: Install MAAS server
        run: |
          set -eux
          sudo --user $(id --user --name) \
            ./create.sh \
            --debug \
            --console \
            --series bionic \
            --maas-channel 2.7 \
            --juju-channel 2.8 \
            --maas-deb \
            --postgresql
