name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install packages
        run: |
          set -eux
          sudo apt update
          sudo apt install --yes \
            python3-pip \
            qemu-system \
            libvirt-daemon-system
          pip install bashate

      - name: Set up user accounts
        run: sudo usermod --append --groups libvirt $(id --user --name)

      - name: Lint
        run: bashate --verbose --ignore E006,E044 *.sh
